name: Deploy to Sonatype repository

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # WebFX requires at least JDK 13 due to javac bugs in prior versions (otherwise JDK 11+ should be enough in theory)
      jdk-version: '19'

    steps:

      # Set up the JDK and Maven settings.xml
      - name: Set up JDK ${{ env.jdk-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.jdk-version }}
          server-id: webfx-sonatype-deploy
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD

      # Checkout this repository
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Deploy webfx-maven-plugin
        run: mvn -B deploy
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
